export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const ADD_INGREDIENT_BUN = "ADD_INGREDIENT_BUN";
export const ADD_INGREDIENT_OTHER = "ADD_INGREDIENT_OTHER";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const SORT_INGREDIENT = "SORT_INGREDIENT";
